### ISSUE TITLE
Position and size not correct until zoomed or panned

### ISSUE THREAD

**Issue by jrjdavidson** [antonioxdias/OpenSeadragonHTMLelements#11]
When I add elements the position and zoom of the element is not correct until the viewer is panned or zoomed. Tested in chrome and firefox, issue is present in both.

**Comment by antonioxdias** [comment]
In what conditions does this occur? Can you provide a bit more context (or better yet, a code demo in a sandbox 👨‍💻 ).
When are you adding the element?

**Comment by jrjdavidson** [comment]
Here is what I was playing with earlier, click on next and the overlay appears at 4/6 https://www.holoceneadventures.com/GEOL242/2021/Lab9Textures/GN1Other.html

**Comment by antonioxdias** [comment]
I see the issue. Seem that calling the repositionElements function when adding the element should fix it.
Just pushed this change into the Master branch. Care to update to the latest version and try again?

I must say, your demo it's a pretty interesting use case!

**Comment by jrjdavidson** [comment]
Sorted thanks, works great now.

And thanks for the compliment- I help create online labs and this one is helping students learn how to identify minerals under the microscope. It's pretty neat!
