### ISSUE TITLE
HTML Link in textbox innerHTML does not work

### ISSUE THREAD

**Issue by liveman1** [antonioxdias/OpenSeadragonHTMLelements#13]
Hi,
I would like to add a link.
Something like this:
var textbox = document.createElement('div')
      textbox.style.backgroundColor = 'rgba(200,200,200,0.8)'
      textbox.style.border = 'solid 1px black'
      textbox.style.borderRadius = '8px'
      textbox.innerHTML =
        '<a href="_top" class="mylink">Link</a>'

The link is shown. However, when clicking on it it zooms in further instead of opening the link.
Is there any other way to add links?

Thanks a lot!

**Comment by antonioxdias** [comment]
Hey hey!

I'm sure there's a better way to achieve your desired behaviour. But the first quick and dirty way that comes to mind is to enable/disable the viewer controls when the users' mouse leaves/enters your link component.

```
<a
  onmouseenter="viewer.setMouseNavEnabled(false)"
  onmouseleave="viewer.setMouseNavEnabled(true)"
  href="https://www.github.com"
  target="_blank"
  rel="noopener noreferrer"
>
  my link
</a>
```

Hope that helps

**Comment by liveman1** [comment]
Hi Antonio, thanks a lot for your help :)
I will give it a try & post if it works.
Best regards!

**Comment by liveman1** [comment]
Awesome! Works perfect!
Thanks a lot
