### ISSUE TITLE
Uncaught ReferenceError: textbox is not defined

### ISSUE THREAD

**Issue by gregory-chatelier** [antonioxdias/OpenSeadragonHTMLelements#5]
Hi, thank you for that plugin. Really helpfull.

Resizing a div with text content doesn't work in my case :

`Uncaught ReferenceError: textbox is not defined
    at repositionElement (OpenSeadragonHTMLelements.js:142)
    at repositionElements (OpenSeadragonHTMLelements.js:123)
    at Object.handler (OpenSeadragonHTMLelements.js:34)
    at eventsource.js:162
    at e.Viewer.raiseEvent (eventsource.js:184)
    at viewer.js:3336
    at b (viewer.js:3240)
    at viewer.js:2428`

I have had to change that line

`  if ("fontSize" in e) {
    textbox.style.fontSize = (
      e.fontSize * viewer.viewport.getZoom(true) / viewer.viewport.getHomeZoom()
    ) + "px"
  }`

into

`  if ("fontSize" in e) {
    e.element.style.fontSize = (
      e.fontSize * viewer.viewport.getZoom(true) / viewer.viewport.getHomeZoom()
    ) + "px"
  }`

**Comment by antonioxdias** [comment]
Hey hey!

Nice catch! That was a big overlook on my part. It actually works in the demo as my the text demoing div is store in var textbox, hence the mistake.

Would be great if you open a pull request, so we get your fix into the release!

Thanks :+1:

**Comment by antonioxdias** [comment]
It's been quite a long time, i'll fix this in the next merge and close the issue.
