### ISSUE TITLE
Implementing polygon areas with mouseover effect

### ISSUE THREAD

**Issue by Khamsin1990** [antonioxdias/OpenSeadragonHTMLelements#6]
Hi,

i've been searching the web for quite some time now but i did not find any solution. So i'll post my question here, hoping that someone can help.

Is it possible with openseadragonHTMLelements to add a polygonal area wich will change background colour, etc. while mouseover?

In fact i am allready failing in creating a polygonal element at all... so far i have only worked with html and css and am a bit screwed up with javascript.

I would be very happy about any help! :)

**Comment by antonioxdias** [comment]
Hello there!

First of all, thanks for checking out the plugin, and asking out.
Second, i don't think this is the plugin you're looking for 😄 . It could be done, but you'd be better off using a canvas. I've implemented similar interactions as the one you are describing. This is much simpler to achieve using HTML's canvas to draw the polygon you need. 

Luckily, there are a couple of plugins that already implement proper interactions with OpenSeadragon!
Take a look at [OpenseadragonFabricjsOverlay](https://github.com/altert/OpenseadragonFabricjsOverlay) and [OpenSeadragonPaperjsOverlay](https://github.com/eriksjolund/OpenSeadragonPaperjsOverlay). Both frameworks, Fabricjs and Paperjs, are easy to work with, will allow you to draw your polygon and have it move and resize with OSD. From there you can access event listeners that can do any modifications to your polygon!

I've used both frameworks before and can vouch for either one, so the choice is really up to you! (Though i can't deny i've used paper far more than fabric.)

Hope this answered your question 👍

**Comment by Khamsin1990** [comment]
Hey, thank you very much!!

this helped me a lot, it seems i will still need some help, but i am a big step further then i've been yesterday. :)

again, thanks so much!
