### ISSUE TITLE
Possible to change position/update position

### ISSUE THREAD

**Issue by janokay** [antonioxdias/OpenSeadragonHTMLelements#7]
Hello, 

is there a function to update the position of the HTML element overlays? I tried to access the Elements array and change the x+y values but the position on screen is not updated... can someone help me to find a solution? Thank you!

**Comment by antonioxdias** [comment]
Hello there. There wasn't a function for that, but i just added it, as it seemed like an easy and appropriate feature. Thanks for bringing it up! Check the [demo](https://antonioxdias.github.io/OpenSeadragonHTMLelements/)

So, your reasoning is pretty on point. First you update the x,y values of your element, by setting the rectangle with new values. but then you need to let the page know something changed with the element, so it can be redrawn. This would already occur when several OSD handlers get called `("open", "animation", "rotate", "flip", "resize")` , but in this case it makes sense to go ahead and update that element as soon as the position changes.

You can now just do `moveElement(elementId, newX, newY)` !

I strongly recommend you take your time and analyse the implementation, so you learn from it.

Cheers 🙃

**Comment by janokay** [comment]
Wow! Thank you so much @antonioxdias - I now understand how this works. I also added new width/height to the function on my own. I'm still new to this stuff (also github pull requests)... thank you :)

**Important: i think the demo doesn't work probably anymore!**
